{% set name = "mysql-connector-python" %}
{% set version = "8.0.16" %}
{% set sha256 = "00c2440bd7ce4db8fd78ac0176fa03d8aaf7d18d9f70ba7fcf61ebf02f21873b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Typecast-password-to-const-char-explicitly-py3.patch
    - 0002-Cast-uint-to-enum-mysql_enum_shutdown_level-explicit.patch
    - 0001-wtf2.patch

build:
  number: 0
  # VS 2008 is not supported for libprotobuf
  skip: True  # [win and py2k]
  # https://bugs.python.org/issue1222585
  script: CC=$CXX CFLAGS=$CXXFLAGS python setup.py install --with-protobuf-include-dir=$PREFIX/include --with-protobuf-lib-dir=$PREFIX/lib --with-protoc=$PREFIX/bin/protoc --with-mysql-capi=$PREFIX  # [unix]
  script: python setup.py install --with-protobuf-include-dir=%LIBRARY_INC% --with-protobuf-lib-dir=%LIBRARY_LIB% --with-protoc=%LIBRARY_BIN%/protoc.exe --with-mysql-capi=%LIBRARY_PREFIX% --extra-compile-args=/DPROTOBUF_USE_DLLS  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - mysql-connector-c
    - libprotobuf
    - protobuf >=3.0.0

  run:
    - python
    - protobuf >=3.0.0

test:
  imports:
    - mysql
    - mysql.connector
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python driver for communicating with MySQL servers'

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
