{% set name = "mysql-connector-python" %}
{% set version = "8.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 968323a49d8100c5660a5f4d1f07a27982de07e6fe6cec21bcd55cfcacc9501e
  patches:
    - patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    - patches/0002-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0003-Fix-indentation-for-common-flags.patch
    - patches/0004-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0005-Replace-google-protobuf-string-with-std-string.patch
    - patches/0006-Delete-openssl-vendor-ed-libs-only-if-provided.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config
  host:
    - python
    - pip
    - mysql-devel {{ version }}
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mysql
    - mysql.connector


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers
  dev_url: https://github.com/mysql/mysql-connector-python/
  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
    - xhochy
