{% set name = "mysql-connector-python" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 29a7cb0b24a4f5ccda597c211254db8377493e95e36ca4ee05b15dba6e9c6e78
  patches:
    - patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    - patches/0002-Cast-uint-to-enum-mysql_enum_shutdown_level-explicit.patch
    - patches/0003-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0004-Fix-indentation-for-common-flags.patch
    - patches/0005-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0006-Replace-google-protobuf-string-with-std-string.patch
    - patches/0007-Delete-openssl-vendor-ed-libs-only-if-provided.patch
    - patches/0008-Use-C-17.patch
    - patches/0009-Be-compatible-with-current-libprotobuf-pin.patch
    - patches/0010-Link-to-abseil_dll-on-Windows.patch

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libprotobuf
    - pkg-config
  host:
    - python
    - pip
    - mysql-devel {{ version }}
    - libprotobuf
    - protobuf
    - zlib
  run:
    - python
    - protobuf
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mysql
    - mysql.connector
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers
  dev_url: https://github.com/mysql/mysql-connector-python/
  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
    - xhochy
