{% set name = "mysql-connector-python" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 29a7cb0b24a4f5ccda597c211254db8377493e95e36ca4ee05b15dba6e9c6e78
  patches:
    - patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    - patches/0002-Cast-uint-to-enum-mysql_enum_shutdown_level-explicit.patch
    - patches/0003-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0004-Fix-indentation-for-common-flags.patch
    - patches/0005-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0006-Replace-google-protobuf-string-with-std-string.patch
    - patches/0007-Delete-openssl-vendor-ed-libs-only-if-provided.patch

build:
  number: 0
  script: PROTOBUF_INCLUDE_DIR=$PREFIX/include PROTOBUF_LIB_DIR=$PREFIX/lib PROTOC=$BUILD_PREFIX/bin/protoc MYSQL_CAPI=$PREFIX pip install . --no-deps --verbose  # [unix]
  script: set "PROTOBUF_INCLUDE_DIR=%LIBRARY_INC%" & set "PROTOBUF_LIB_DIR=%LIBRARY_LIB%" & set "PROTOC=%LIBRARY_BIN%/protoc.exe" & set "MYSQL_CAPI=%LIBRARY_PREFIX%" & set "EXTRA_COMPILE_ARGS=/DPROTOBUF_USE_DLLS" & set "SKIP_VENDOR=1" & pip install . --no-deps --verbose  # [win]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libprotobuf
  host:
    - python
    - pip
    - mysql-devel {{ version }}
    - libprotobuf
    - protobuf
    - zlib
  run:
    - python
    - protobuf

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mysql
    - mysql.connector
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers
  dev_url: https://github.com/mysql/mysql-connector-python/
  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
    - xhochy
