{% set name = "mysql-connector-python" %}
{% set version = "8.0.11" %}
{% set sha256 = "b6410ae31d5accc21aac046efe57544c2bd72e3005d78a26b3b4d3efbddce242" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --with-protobuf-include-dir=$PREFIX/include --with-protobuf-lib-dir=$PREFIX/lib --with-protoc=$PREFIX/bin/protoc  # [linux or osx]
  script: python setup.py install --with-protobuf-include-dir=%LIBRARY_INC% --with-protobuf-lib-dir=%LIBRARY_LIB% --with-protoc=%LIBRARY_BIN%/protoc.exe  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - libprotobuf
    - protobuf >=3.0.0

  run:
    - python
    - protobuf >=3.0.0

test:
  imports:
    - mysql
    - mysql.connector
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python driver for communicating with MySQL servers'

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.  
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
