{% set name = "mysql-connector-python" %}
{% set version = "9.0.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 72c75ccb759cee31474906538b3132f3e26bc91d2913b415ea10d699876dbf9c
  patches:
    - patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    - patches/0002-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0003-Fix-indentation-for-common-flags.patch
    - patches/0004-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0005-Delete-openssl-vendor-ed-libs-only-if-provided.patch

build:
  number: 1
  # This is used for linking and building some tools but there is no C++ dependency on the final binaries.
  ignore_run_exports_from:
    - {{ compiler('cxx') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - python
    - pip
    - mysql-devel {{ major_minor }}
    - zlib  # [linux]
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mysql
    - mysql.connector


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers
  dev_url: https://github.com/mysql/mysql-connector-python/
  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
    - xhochy
