{% set name = "mysql-connector-python" %}
{% set version = "8.0.24" %}
{% set sha256 = "590b8f8471f6a72a817bad437b3cb09ddea24e988663c643adaf3a7b4ebbd514" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Typecast-password-to-const-char-explicitly-py3.patch
    - 0002-Cast-uint-to-enum-mysql_enum_shutdown_level-explicit.patch
    - 0003-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - 0004-Fix-indentation-for-common-flags.patch

build:
  number: 0
  # VS 2008 is not supported for libprotobuf
  skip: true  # [win and py2k]
  script: python setup.py install --with-protobuf-include-dir=$PREFIX/include --with-protobuf-lib-dir=$PREFIX/lib --with-protoc=$PREFIX/bin/protoc --with-mysql-capi=$PREFIX  # [unix]
  script: python setup.py install --with-protobuf-include-dir=%LIBRARY_INC% --with-protobuf-lib-dir=%LIBRARY_LIB% --with-protoc=%LIBRARY_BIN%/protoc.exe --with-mysql-capi=%LIBRARY_PREFIX% --extra-compile-args=/DPROTOBUF_USE_DLLS  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - mysql-devel {{ version }}
    - libprotobuf
    - protobuf >=3.0.0

  run:
    - python
    - protobuf >=3.0.0
    - dnspython >=1.16.0

test:
  imports:
    - mysql
    - mysql.connector
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
