travis:
  secure:
    BINSTAR_TOKEN: QZbBlynORROGsNUE4gCwV+KqgrmpAoC1LrgOM17Dl+1hW9bc1GSAXuNADznXgOtWEydBDJ/bn3lzQAjyyrWfI8DDuweShhG/Ccsk2AtEiGUYrnHDCkpZSdqqZ0ESMSi7XRv/HfyE2fi4Mcwxfxq1+qsFYTP8pndoNqK7Vb5/gayQ7zr1q/yb2PolqxQFnuOEEm4a3jxhdjd1Zf2JI79nCD+M1DjF3WjJaPOxuKBtroiO/OT8X4QSCgrMlvY41zs07ZaGNgff3z3ABPAJL5d9miy0yX+imqtR6RDp34Wt7GBubZCNz1vM6gmsCSSjbWWHK9FWfa0Q6/gIZ/6PleWYGUEtW2OV+igZ41UsuVda7wlhJIUoIMjpPRIu9LckFmpPHM/cK1RAHQBkDenkyghF4rZmEj2QKp2wAVps8v9eGptyO0mMQGwm62I8ZA2c4Hu8Uuvsq5302enZXHqnk8pD8VgzvNgpzKAZi6PnQGkXeNopEUNc1tm0mZRhNaWG2JFp8Ti9J8w9LE+NE2U36nQHWB7QTWs2j77qFdzU+HZY17ecptNFJCP7Zfhwf0T3LjWhVs16QUY4rclbtPfXSchW7WDJjOio/DlK5LcpB5FuG/raGbBeMnQ3/jrSFz2B2IGj5Po9PkYVx47lDn/x0cJrYYoO6s5C02h7D9IWbY5AvhM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
